# -*- coding: utf-8 -*-
"""ReCarmend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSaZ5iqZxeMYemp16GMHhwKpdmzSat9k
"""
import os
import cohere
import pandas as pd
from dotenv import load_dotenv

#carData= pd.read_csv('/content/sample_data/ReCarmmend.csv')# make sure the csv is in the sample folder
"""
csv's may be broken up by car type
"""


#carData = carData.sample(frac = 1).reset_index




load_dotenv()

co = cohere.ClientV2(os.getenv("CO_API_KEY"))
inputType = 0

maximumPrice = -1
maximumMileage = -1
color = 'Null'
make = 'Null'
model = 'Null'
minYear = -1
maxYear = 2026
carType = 'Null'
while inputType not in(1, 2):
  inputType = int(input("filter search or AI search?(1/2): "))

if(inputType == 1):
  print("If these filters are not relevant to you please input -1")
  maximumPrice = input("What is the max acceptable price: ")
  maximumMileage = input("What is the max acceptable mileage: ")
  minYear = input("What is the earliest year : ")
  maxYear = input("What is the latest year (put the current year if this filter is not inportant to you): ")

  print("If these filters are not relevant to you please input null")
  color = input("What is the desired color: ")
  make = input("What is the desired maker: ")
  model = input("What is the desired model: ")
  carType = input("What is the desired car type: ")#(Convertible, Coupe, Hatchback, Hybrid, Sedan, SUV, Minivan, Pickup Truck)
  print(maximumPrice, maximumMileage, color, make, model, minYear, maxYear, carType)


if(inputType == 2):
  prompt = input("describe the kind of car you would want: ")
  response = co.chat(
        model="command-a-03-2025",
        messages=[{"role": "user", "content": prompt + "Please take the prompt above and isolate the desired model, make, year range, maximum price, color, maximum mileage, and car type.If the prompt given does not relate to cars please ignore the prompt entirely and print nothing more than this prompt does not relate to cars.If An exact color is not specified please return it as null, a color should be given if it is a very general color ex(red orange yellow green blue, black, white, silver NOT matte black or platinum silver) if the given prompt does not include information for Color, Make or Model and car types please return it as 'null'.If multiple makes are given please select only 1. possible car types are Convertible, Coupe, Hatchback, Hybrid, Sedan, SUV, Minivan, Pickup Truck, if one of these is not specified please return null. If it does not include information for Maximum Price, MAximum Mileage, or Min/max year please return it as 0 Do not include any addition text.The current year is 2026. Please format the output as Maximum Price: Maximum Mileage: Car type: Color: Make: Model: Minimum Year: Maximum Year: "}]
        )
  rawText = response.message.content[0].text
  parsed = {}
  for line in rawText.split("\n"):
    if ":" in line:
      key,value = line.split(":", 1)
      parsed[key.strip()] = value.strip()
    maximumPrice = parsed.get("Maximum Price", 0)
    maximumMileage = parsed.get("Maximum Mileage", 0)
    color = parsed.get("Color", "Null")
    make = parsed.get("Make", "Null")
    model = parsed.get("Model", "Null")
    minYear = parsed.get("Minimum Year", 0)
    maxYear = parsed.get("Maximum Year", 0)
    carType = parsed.get("Car type", "Null")
    print("A.I. and our program may not always be able to understand the input given, if you see results that you do not desire we recommend searching with more explicity stated wants")
    print("If your prompt does not contain information about cars then you will simply see the first 10 cars listed in our database")
    print(" ")
    print("Based on your prompts this is the requirements the system is looking for")
    print(rawText)


  print(maximumPrice, maximumMileage, color, make, model, minYear, maxYear, carType)

#Wi ya webscraping goes here